sudo: true
dist: trusty

language: cpp

before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce

script:
  - docker build -t dit168.marble -f Dockerfile .
  - docker build -t dit168.marble-armhf -f Dockerfile.armhf .
  - docker build -t dit168.marble-ubuntu -f Dockerfile.ubuntu .
  - docker build -t dit168.marble-ubuntu-armhf -f Dockerfile.ubuntu-armhf .

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker tag dit168.marble $DOCKER_USERNAME/dit168.marble:latest;
    docker tag dit168.marble-armhf $DOCKER_USERNAME/dit168.marble:latest-armhf;
    docker tag dit168.marble-ubuntu $DOCKER_USERNAME/dit168.marble:latest-ubuntu;
    docker tag dit168.marble-ubuntu-armhf $DOCKER_USERNAME/dit168.marble:latest-ubuntu-armhf;
    docker push $DOCKER_USERNAME/dit168.marble:latest;
    docker push $DOCKER_USERNAME/dit168.marble:latest-armhf;
    docker push $DOCKER_USERNAME/dit168.marble:latest-ubuntu;
    docker push $DOCKER_USERNAME/dit168.marble:latest-ubuntu-armhf;
    fi
