sudo: true
dist: trusted

language: cpp

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

before_install:
  - docker build -t dit168.marble -f Dockerfile .

script:
#  ...

after_success:
#  - if [ "$TRAVIS_BRANCH" == "master" ]; then
#    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
#    docker push USER/REPO;
#    fi