sudo: true
dist: trusted

language: cpp

before_install:
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce

script:
  - docker build -t dit168.marble -f Dockerfile .

after_success:
#  - if [ "$TRAVIS_BRANCH" == "master" ]; then
#    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
#    docker push USER/REPO;
#    fi