version: '2'
services:
    odsupercomponent:
        image: seresearch/2018-dit-168:v0.3.5-armhf
        network_mode: "host"
        restart: always
        volumes:
        - .:/opt/miniature.data
        command: "/opt/od4/bin/odsupercomponent --cid=160 --verbose=1 --configuration=/opt/miniature.data/configuration"

    proxy-miniature-pwm-motor:
        image: seresearch/2018-dit-168:v0.3.5-armhf
        depends_on:
        - odsupercomponent
        network_mode: "host"
        restart: always
        privileged: true
        volumes:
        - /sys/:/sys/
        - /dev/:/dev/
        command: "/opt/opendlv.miniature/bin/opendlv-proxy-miniature-pwm-motor --cid=160 --freq=50 --id=1"

    MARBLE.DS4:
        image: gusbocju/dit168.marble:latest-ubuntu-armhf
        network_mode: "host"
        restart: always
        devices:
        - /dev/input/js0:/dev/input/js0
        command: "/opt/MARBLE.DS4 --cid=160 --freq=100 --dev=/dev/input/js0"

    MARBLE.V2V:
        image: gusbocju/dit168.marble:latest-armhf
        network_mode: "host"
        restart: always
        command: "/opt/MARBLE.V2V --cid=160 --freq=10 --ip=172.20.10.12 --id=5"

    dit168-signal-viewer:
        image: gusbocju/dit168.marble:latest-armhf
        network_mode: "host"
        restart: always
        command: "/opt/bin/websocketd --staticdir=/opt/signal-viewer --port=8080 --binary=true /bin/cluon-OD4toStdout"