version: '2'
services:
    odsupercomponent:
        image: seresearch/2018-dit-168:v0.3.5-armhf
        network_mode: "host"
        restart: always
        volumes:
        - .:/opt/miniature.data
        command: "/opt/od4/bin/odsupercomponent --cid=160 --verbose=1 --configuration=/opt/miniature.data/configuration"

    proxy-miniature-pwm-motor:
        image: seresearch/2018-dit-168:v0.3.5-armhf
        depends_on:
        - odsupercomponent
        network_mode: "host"
        restart: always
        privileged: true
        volumes:
        - /sys/:/sys/
        - /dev/:/dev/
        command: "/opt/opendlv.miniature/bin/opendlv-proxy-miniature-pwm-motor --cid=160 --freq=50 --id=1"

    MARBLE.DS4:
        image: gusbocju/dit168.marble:latest-ubuntu-armhf
        network_mode: "host"
        restart: always
        devices:
        - /dev/input/js0:/dev/input/js0
        command: "/opt/MARBLE.DS4 --cid=160 --freq=50 --safety-distance=35 --dev=/dev/input/js0"

    MARBLE.V2V:
        image: gusbocju/dit168.marble:latest-armhf
        network_mode: "host"
        restart: always
        command: "/opt/MARBLE.V2V --cid=160 --freq=10 --safety-distance=35 --ip=172.20.10.12 --id=5"

    opendlv-signal-viewer:
        image: gusbocju/dit168.marble:latest-ubuntu-armhf
        network_mode: "host"
        ports:
        - 8081:8081
        restart: always
        command: "/opt/bin/websocketd --staticdir=/opt/signal-viewer --port=8081 --binary=true /usr/bin/cluon-OD4toStdout --cid=160"

    device-ultrasonic-srf08-front:
        image: chalmersrevere/opendlv-device-ultrasonic-srf08-armhf:v0.0.6
        network_mode: "host"
        devices:
        - /dev/i2c-1:/dev/i2c-1
        restart: always
        command: "/usr/bin/opendlv-device-ultrasonic-srf08 --dev=/dev/i2c-1 --bus-address=113 --cid=160 --freq=10 --id=0"
